### Import Library

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Load dataset

In [3]:
df = pd.read_csv('../data/woe_feature_engineering.csv')
df

Unnamed: 0         TransactionId         BatchId       AccountId  \
0               0   TransactionId_76871   BatchId_36123  AccountId_3957   
1               1   TransactionId_73770   BatchId_15642  AccountId_4841   
2               2   TransactionId_26203   BatchId_53941  AccountId_4229   
3               3     TransactionId_380  BatchId_102363   AccountId_648   
4               4   TransactionId_28195   BatchId_38780  AccountId_4841   
...           ...                   ...             ...             ...   
95657       95657   TransactionId_89881   BatchId_96668  AccountId_4841   
95658       95658   TransactionId_91597    BatchId_3503  AccountId_3439   
95659       95659   TransactionId_82501  BatchId_118602  AccountId_4841   
95660       95660  TransactionId_136354   BatchId_70924  AccountId_1346   
95661       95661   TransactionId_35670   BatchId_29317  AccountId_4841   

            SubscriptionId       CustomerId  CountryCode  ProviderId  \
0       SubscriptionId_887  CustomerId_4406          0.0           5   
1      SubscriptionId_3829  CustomerId_4406          0.0           3   
2       SubscriptionId_222  CustomerId_4683          0.0           5   
3      SubscriptionId_2185   CustomerId_988          0.0           0   
4      SubscriptionId_3829   CustomerId_988          0.0           3   
...                    ...              ...          ...         ...   
95657  SubscriptionId_3829  CustomerId_3078          0.0           3   
95658  SubscriptionId_2643  CustomerId_3874          0.0           5   
95659  SubscriptionId_3829  CustomerId_3874          0.0           3   
95660   SubscriptionId_652  CustomerId_1709          0.0           5   
95661  SubscriptionId_3829  CustomerId_1709          0.0           3   

       ProductId    Amount  ...  ChannelId_ChannelId_2  ChannelId_ChannelId_3  \
0              1  0.092004  ...                  False                   True   
1             19  0.091910  ...                   True                  False   
2              0  0.091958  ...                  False                   True   
3             11  0.093750  ...                  False                   True   
4             19  0.091853  ...                   True                  False   
...          ...       ...  ...                    ...                    ...   
95657         19  0.091820  ...                   True                  False   
95658          1  0.092004  ...                  False                   True   
95659         19  0.091910  ...                   True                  False   
95660          8  0.092188  ...                  False                   True   
95661         19  0.091906  ...                   True                  False   

       ChannelId_ChannelId_5  Recency  Frequency  Monetary  Stability  \
0                      False      1.0   0.028851  0.557522   0.000919   
1                      False      1.0   0.028851  0.557522   0.000919   
2                      False      0.0   0.000244  0.556944   0.000000   
3                      False      1.0   0.009046  0.558153   0.005187   
4                      False      1.0   0.009046  0.558153   0.005187   
...                      ...      ...        ...       ...        ...   
95657                  False      1.0   0.139853  0.569883   0.006814   
95658                  False      1.0   0.010269  0.557249   0.000687   
95659                  False      1.0   0.010269  0.557249   0.000687   
95660                  False      1.0   0.127873  0.561462   0.000969   
95661                  False      1.0   0.127873  0.561462   0.000969   

       RFMS_Score  Risk_Label  RFMS_Binned  
0        0.396823           0          2.0  
1        0.396823           0          2.0  
2        0.139297           0          0.0  
3        0.393097           0          2.0  
4        0.393097           0          2.0  
...           ...         ...          ...  
95657    0.429138           0          2.0  
95658    0.392051           0  

## 5. Train Test Split

### Separet dependant and independant variable

In [4]:
from sklearn.model_selection import train_test_split

# Define features and target variable
X = df.drop(['TransactionId', 'Risk_Label', 'RFMS_Score', 'TransactionId', 'BatchId', 'AccountId', 'SubscriptionId', 'CustomerId', 'CountryCode', 'ProviderId','ProductId','FraudResult'], axis=1)  # Drop non-feature columns
y = df['Risk_Label']

### Split the data to training and Testing Set

In [5]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print("Features (X):")
X.head()

Features (X):


Unnamed: 0    Amount     Value  PricingStrategy  Transaction_Hour  \
0           0  0.092004  0.000101         0.666667                 2   
1           1  0.091910  0.000002         0.666667                 2   
2           2  0.091958  0.000050         0.666667                 2   
3           3  0.093750  0.002206         0.666667                 3   
4           4  0.091853  0.000065         0.666667                 3   

   Transaction_Day  Transaction_Month  Transaction_Year  \
0               15                 11              2018   
1               15                 11              2018   
2               15                 11              2018   
3               15                 11              2018   
4               15                 11              2018   

   Total_Transaction_Amount  Average_Transaction_Amount  ...  \
0                  0.557522                    0.047184  ...   
1                  0.557522                    0.047184  ...   
2                  0.556944                    0.047137  ...   
3                  0.558153                    0.047749  ...   
4                  0.558153                    0.047749  ...   

   ProductCategory_tv  ProductCategory_utility_bill  ChannelId_ChannelId_2  \
0               False                         False                  False   
1               False                         False                   True   
2               False                         False                  False   
3               False                          True                  False   
4               False                         False                   True   

   ChannelId_ChannelId_3  ChannelId_ChannelId_5  Recency  Frequency  Monetary  \
0                   True                  False      1.0   0.028851  0.557522   
1                  False                  False      1.0   0.028851  0.557522   
2                   True                  False      0.0   0.000244  0.556944   
3                   True                  False      1.0   0.009046  0.558153   
4                  False                  False      1.0   0.009046  0.558153   

   Stability  RFMS_Binned  
0   0.000919          2.0  
1   0.000919          2.0  
2   0.000000          0.0  
3   0.005187          2.0  
4   0.005187          2.0  

[5 rows x 28 columns]

In [6]:
X.columns

Index(['Unnamed: 0', 'Amount', 'Value', 'PricingStrategy', 'Transaction_Hour',
       'Transaction_Day', 'Transaction_Month', 'Transaction_Year',
       'Total_Transaction_Amount', 'Average_Transaction_Amount',
       'Transaction_Count', 'Std_Deviation_Transaction_Amount',
       'ProductCategory_data_bundles', 'ProductCategory_financial_services',
       'ProductCategory_movies', 'ProductCategory_other',
       'ProductCategory_ticket', 'ProductCategory_transport',
       'ProductCategory_tv', 'ProductCategory_utility_bill',
       'ChannelId_ChannelId_2', 'ChannelId_ChannelId_3',
       'ChannelId_ChannelId_5', 'Recency', 'Frequency', 'Monetary',
       'Stability', 'RFMS_Binned'],
      dtype='object')

In [7]:
print("\nTarget (y):")
y.head()


Target (y):


0    0
1    0
2    0
3    0
4    0
Name: Risk_Label, dtype: int64

In [8]:
# # Display the size of the train and test sets
print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

Training set size: 76529 samples
Testing set size: 19133 samples


## 6. Model Training
The following classfication model were selected to build credit score reisk classfication

**A. Logistic Regression**

In [9]:
from sklearn.linear_model import LogisticRegression
# Initialize models
log_reg = LogisticRegression(max_iter=1000)

In [10]:
# Train Logistic Regression
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [11]:
# Make predictions
log_reg_preds_test = log_reg.predict(X_test)
log_reg_preds_train = log_reg.predict(X_train)

**B. Random Forest**

In [12]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

In [13]:
# Train Random Forest
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [14]:
# Make predictions
rf_preds_train = rf_model.predict(X_train)
rf_preds_test = rf_model.predict(X_test)

**C.  XGBoost Classfication Model**

In [15]:
# XGBoost model
import xgboost as xgb
xgb_model = xgb.XGBClassifier(eval_metric='mlogloss', random_state=42)

In [16]:
#  Train the XGBoost model 
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=42, ...)

In [17]:
# Make predictions
xgb_train_pred = xgb_model.predict(X_train)
xgb_test_pred = xgb_model.predict(X_test)

**D. Adaboost**

In [18]:
from sklearn.ensemble import AdaBoostClassifier
ada_model = AdaBoostClassifier()

In [19]:
# Adaboost
ada_model.fit(X_train, y_train)

c:\Users\getac\anaconda3\envs\myenve\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier()

In [20]:
# AdaBoost predictions
ada_preds_train = ada_model.predict(X_train)
ada_preds_test = ada_model.predict(X_test)

**E. Decision Tree**

In [21]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()

In [22]:
#decision tree
dt_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [23]:
# Decision Tree predictions
dt_preds_train = dt_model.predict(X_train)
dt_preds_test = dt_model.predict(X_test)

### Performance Evaluation

In [24]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    roc_curve,
    auc,
)

# Define a function to evaluate the model performance
def evaluate_model(y_true, y_preds, model_name):
    accuracy = accuracy_score(y_true, y_preds)
    precision = precision_score(y_true, y_preds)
    recall = recall_score(y_true, y_preds)
    f1 = f1_score(y_true, y_preds)
    roc_auc = roc_auc_score(y_true, y_preds)

    print(f"{model_name} Performance:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print(f"ROC-AUC: {roc_auc:.4f}")
    print(f"Confusion Matrix:\n{confusion_matrix(y_true, y_preds)}\n")

# Evaluate Logistic Regression on training and testing sets
print("Logistic Regression Evaluation on Training Set:")
evaluate_model(y_train, log_reg_preds_train, "Logistic Regression (Train)")
print("Logistic Regression Evaluation on Testing Set:")
evaluate_model(y_test, log_reg_preds_test, "Logistic Regression (Test)")


Logistic Regression Evaluation on Training Set:
Logistic Regression (Train) Performance:
Accuracy: 0.9995
Precision: 0.9961
Recall: 0.9985
F1 Score: 0.9973
ROC-AUC: 0.9991
Confusion Matrix:
[[69913    26]
 [   10  6580]]

Logistic Regression Evaluation on Testing Set:
Logistic Regression (Test) Performance:
Accuracy: 0.9995
Precision: 0.9958
Recall: 0.9982
F1 Score: 0.9970
ROC-AUC: 0.9989
Confusion Matrix:
[[17478     7]
 [    3  1645]]



In [25]:
# Evaluate Random Forest on training and testing sets
print("Random Forest Evaluation on Training Set:")
evaluate_model(y_train, rf_preds_train, "Random Forest (Train)")
print("Random Forest Evaluation on Testing Set:")
evaluate_model(y_test, rf_preds_test, "Random Forest (Test)")

Random Forest Evaluation on Training Set:
Random Forest (Train) Performance:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
ROC-AUC: 1.0000
Confusion Matrix:
[[69939     0]
 [    0  6590]]

Random Forest Evaluation on Testing Set:
Random Forest (Test) Performance:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
ROC-AUC: 1.0000
Confusion Matrix:
[[17485     0]
 [    0  1648]]



In [26]:
# Evaluate XGBoost on training and testing sets
print("XGBoost Evaluation on Training Set:")
evaluate_model(y_train, xgb_train_pred, "Xgboost (Train)")
print("XGboost Evaluation on Testing Set:")
evaluate_model(y_test, xgb_test_pred, "XGBoost (Test)")

XGBoost Evaluation on Training Set:
Xgboost (Train) Performance:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
ROC-AUC: 1.0000
Confusion Matrix:
[[69939     0]
 [    0  6590]]

XGboost Evaluation on Testing Set:
XGBoost (Test) Performance:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
ROC-AUC: 1.0000
Confusion Matrix:
[[17485     0]
 [    0  1648]]



In [27]:
# Decision Tree evaluation
print("Decision Tree Evaluation on Training Set:")
evaluate_model(y_train, dt_preds_train, "Decision Tree (Train)")
print("Decision Tree Evaluation on Testing Set:")
evaluate_model(y_test, dt_preds_test, "Decision Tree (Test)")

Decision Tree Evaluation on Training Set:
Decision Tree (Train) Performance:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
ROC-AUC: 1.0000
Confusion Matrix:
[[69939     0]
 [    0  6590]]

Decision Tree Evaluation on Testing Set:
Decision Tree (Test) Performance:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
ROC-AUC: 1.0000
Confusion Matrix:
[[17485     0]
 [    0  1648]]



In [28]:
# AdaBoost evaluation
print("AdaBoost Evaluation on Training Set:")
evaluate_model(y_train, ada_preds_train, "AdaBoost (Train)")
print("AdaBoost Evaluation on Testing Set:")
evaluate_model(y_test, ada_preds_test, "AdaBoost (Test)")

AdaBoost Evaluation on Training Set:
AdaBoost (Train) Performance:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
ROC-AUC: 1.0000
Confusion Matrix:
[[69939     0]
 [    0  6590]]

AdaBoost Evaluation on Testing Set:
AdaBoost (Test) Performance:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000
ROC-AUC: 1.0000
Confusion Matrix:
[[17485     0]
 [    0  1648]]



In [29]:
import joblib
# Save the models to .pkl files
joblib.dump(log_reg, 'model/logistic_regression_model.pkl')
joblib.dump(rf_model, 'model/random_forest_model.pkl')
joblib.dump(dt_model, 'model/decision_tree_model.pkl')
joblib.dump(ada_model, 'model/adaboost_model.pkl')

print("Models saved as .pkl files.")

Models saved as .pkl files.
